import streamlit as st
from google import genai

st.set_page_config(page_title="AI Marketing Strategy Studio", page_icon="🎯", layout="wide")

st.markdown("""
<style>
.stApp {background:#0b1020;color:#f4f6ff}
.block-container {max-width:1150px;padding-top:2rem;padding-bottom:3rem}
.hero {padding:1.6rem 1.8rem;border-radius:18px;background:linear-gradient(120deg,#20144b,#172554);border:1px solid #38366b;margin-bottom:1.2rem}
.hero h1 {margin:0;color:white}.hero p {color:#d7dcf5;margin-bottom:0}
div[data-testid="stMetric"] {background:#121a30;border:1px solid #283653;padding:1rem;border-radius:14px}
section[data-testid="stSidebar"] {background:#0e1528}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="hero">
<h1>🎯 AI Marketing Strategy Studio</h1>
<p>A sequential two-agent workflow: Marketing Strategist → Content Creator</p>
</div>
""", unsafe_allow_html=True)

st.write("Create a campaign strategy and marketing content for your product. The second AI step uses the strategy generated by the first step.")

with st.sidebar:
    st.header("Campaign details")
    product = st.text_input("Product", "Lightweight water bottle")
    audience = st.text_input("Target audience", "School children aged 6–16, with parents/guardians as purchasers")
    budget = st.number_input("Marketing budget (USD)", min_value=100, max_value=1_000_000, value=2000, step=100)
    market = st.text_input("Market / location", "United States")
    goal = st.selectbox("Main campaign goal", ["Increase awareness", "Drive online sales", "Generate website traffic", "Build social media engagement", "Promote a product launch"])
    tone = st.selectbox("Content tone", ["Fun and friendly", "Educational", "Energetic", "Premium", "Eco-conscious"])
    extra = st.text_area("Extra details (optional)", placeholder="Price, product features, available channels, campaign dates…")
    run = st.button("Generate campaign", type="primary", use_container_width=True)

if run:
    api_key = st.secrets.get("GEMINI_API_KEY", "")
    if not api_key:
        st.error("Gemini API key is missing. Add GEMINI_API_KEY under Streamlit Cloud → App settings → Secrets.")
        st.stop()
    if not product.strip() or not audience.strip():
        st.warning("Please enter both a product and target audience.")
        st.stop()

    client = genai.Client(api_key=api_key)
    model = "gemini-2.5-flash"

    strategy_prompt = f"""You are Agent 1, the Marketing Strategist, in a sequential AI workflow.
Create a practical marketing plan from these details:
Product: {product}
Target audience: {audience}
Budget: USD {budget}
Market: {market}
Campaign goal: {goal}
Extra details: {extra or 'Not provided'}

Include: (1) campaign objective and audience insight, (2) 3–5 marketing channels with reasons,
(3) a budget allocation that adds up exactly to USD {budget}, (4) a four-week timeline,
(5) measurable KPIs, (6) assumptions and risks. Do not guarantee results. If the audience includes
minors, consider child privacy and avoid manipulative pressure; distinguish children from adult purchasers.
"""

    with st.spinner("Agent 1 — developing the marketing strategy…"):
        try:
            response1 = client.models.generate_content(model=model, contents=strategy_prompt)
            strategy = response1.text or "No strategy was returned. Please try again."
        except Exception as exc:
            st.error(f"Strategy generation failed: {exc}")
            st.stop()

    content_prompt = f"""You are Agent 2, the Content Creator. You MUST use the strategy from Agent 1 below.
Product: {product}
Target audience: {audience}
Market: {market}
Tone: {tone}
Campaign goal: {goal}

Create: 3 short social posts with calls to action; one 15–20 second Reel/video concept and script;
2 tagline/headline options; one message aimed at parents/guardians; and a note explaining which channel
fits each item. Keep claims truthful and do not invent product features or unsupported health/environmental claims.
Because children may be part of the audience, avoid manipulative pressure and do not ask children to share personal data.

STRATEGY FROM AGENT 1:
{strategy}
"""
    with st.spinner("Agent 2 — creating content based on the strategy…"):
        try:
            response2 = client.models.generate_content(model=model, contents=content_prompt)
            content = response2.text or "No content was returned. Please try again."
        except Exception as exc:
            st.error(f"Content generation failed: {exc}")
            st.stop()

    st.success("Campaign generated.")
    tab1, tab2, tab3 = st.tabs(["📊 Strategy", "✍️ Content", "📥 Export report"])
    with tab1:
        st.markdown(strategy)
    with tab2:
        st.markdown(content)
    with tab3:
        report = f"# AI Marketing Campaign\n\n## Campaign details\n- Product: {product}\n- Target audience: {audience}\n- Budget: USD {budget}\n- Market: {market}\n- Goal: {goal}\n\n## Agent 1 — Marketing Strategy\n\n{strategy}\n\n## Agent 2 — Content Creator\n\n{content}\n"
        st.download_button("Download campaign report (.md)", data=report, file_name="ai_marketing_campaign.md", mime="text/markdown")
else:
    a, b, c = st.columns(3)
    a.metric("AI steps", "2 agents")
    b.metric("Workflow", "Sequential")
    c.metric("Example budget", "$2,000")
    st.markdown("### How it works")
    st.markdown("""
1. **Marketing Strategist:** reviews the product, audience, goal and budget.
2. **Content Creator:** receives the strategy from Agent 1 and creates channel-specific content.
3. **Export:** view both results and download a Markdown report.

**Note:** AI suggestions are drafts. Review budget assumptions and campaign claims before using them in a real campaign.
""")

st.divider()
st.caption("AI Marketing Strategy Studio · Built with Python, Streamlit and Google Gemini")
